<?php
	namespace PHPSTORM_META {
	/** @noinspection PhpUnusedLocalVariableInspection */
	/** @noinspection PhpIllegalArrayKeyTypeInspection */
	$STATIC_METHOD_TYPES = [

		\D('') => [
			'TalkMessagePush' instanceof Common\Model\TalkMessagePushModel,
			'InviteUserInfo' instanceof Ucenter\Model\InviteUserInfoModel,
			'Action' instanceof Admin\Model\ActionModel,
			'Role' instanceof Admin\Model\RoleModel,
			'TalkPush' instanceof Common\Model\TalkPushModel,
			'UserConfig' instanceof Ucenter\Model\UserConfigModel,
			'Menu' instanceof Admin\Model\MenuModel,
			'Attachment' instanceof Addons\Attachment\Model\AttachmentModel,
			'TalkMessage' instanceof Common\Model\TalkMessageModel,
			'Expression' instanceof Core\Model\ExpressionModel,
			'Relation' instanceof Think\Model\RelationModel,
			'Invite' instanceof Ucenter\Model\InviteModel,
			'LocalComment' instanceof Addons\LocalComment\Model\LocalCommentModel,
			'User' instanceof Common\Model\UserModel,
			'Picture' instanceof Home\Model\PictureModel,
			'Theme' instanceof Common\Model\ThemeModel,
			'View' instanceof Think\Model\ViewModel,
			'Version' instanceof Admin\Model\VersionModel,
			'SeoRule' instanceof Common\Model\SeoRuleModel,
			'Verify' instanceof Common\Model\VerifyModel,
			'UserTagLink' instanceof Ucenter\Model\UserTagLinkModel,
			'Document' instanceof Admin\Model\DocumentModel,
			'AdvPos' instanceof Common\Model\AdvPosModel,
			'InviteBuyLog' instanceof Ucenter\Model\InviteBuyLogModel,
			'Tree' instanceof Common\Model\TreeModel,
			'Url' instanceof Admin\Model\UrlModel,
			'Follow' instanceof Common\Model\FollowModel,
			'ContentHandler' instanceof Common\Model\ContentHandlerModel,
			'IssueContent' instanceof Issue\Model\IssueContentModel,
			'Mongo' instanceof Think\Model\MongoModel,
			'IMe' instanceof Common\Model\IMessage,
			'Module' instanceof Common\Model\ModuleModel,
			'Channel' instanceof Common\Model\ChannelModel,
			'AuthRule' instanceof Admin\Model\AuthRuleModel,
			'Member' instanceof Common\Model\MemberModel,
			'Report' instanceof Addons\Report\Model\ReportModel,
			'RoleConfig' instanceof Admin\Model\RoleConfigModel,
			'Talk' instanceof Common\Model\TalkModel,
			'Sina' instanceof Addons\SyncLogin\Model\SinaModel,
			'File' instanceof Home\Model\FileModel,
			'Issue' instanceof Issue\Model\IssueModel,
			'ActionLimit' instanceof Common\Model\ActionLimitModel,
			'Sso' instanceof Admin\Model\SsoModel,
			'AuthGroup' instanceof Admin\Model\AuthGroupModel,
			'Support' instanceof Common\Model\SupportModel,
			'Cx' instanceof Cx\Model\CxModel,
			'Info' instanceof Addons\SyncLogin\Model\InfoModel,
			'Config' instanceof Admin\Model\ConfigModel,
			'Title' instanceof Ucenter\Model\TitleModel,
			'Message' instanceof Common\Model\MessageModel,
			'District' instanceof Addons\ChinaCity\Model\DistrictModel,
			'Score' instanceof Ucenter\Model\ScoreModel,
			'Hooks' instanceof Admin\Model\HooksModel,
			'InviteLog' instanceof Ucenter\Model\InviteLogModel,
			'Addons' instanceof Admin\Model\AddonsModel,
			'Adv' instanceof Think\Model\AdvModel,
			'SuperLinks' instanceof Addons\SuperLinks\Model\SuperLinksModel,
			'UserTag' instanceof Ucenter\Model\UserTagModel,
			'Curl' instanceof Admin\Model\CurlModel,
			'InviteType' instanceof Ucenter\Model\InviteTypeModel,
			'UcenterMember' instanceof User\Model\UcenterMemberModel,
			'CheckIn' instanceof Addons\CheckIn\Model\CheckInModel,
			'PinYin' instanceof Common\Model\PinYinModel,
		],
		\DL('') => [
			'DownloadLogic' instanceof Admin\Logic\DownloadLogic,
			'ArticleLogic' instanceof Admin\Logic\ArticleLogic,
			'BaseLogic' instanceof Admin\Logic\BaseLogic,
		],
	];
}